import {
  ApplicantMatchDetailSchema,
  DeleteRecruitingOpinionResultSchema,
  DeleteRecruitingReviewResultSchema,
  ListRecruitingApplicantMatchesResultSchema,
  ListRecruitingOpinionsResultSchema,
  ListRecruitingReviewsResultSchema,
  OpinionDetailSchema,
  RecruitingOpinionMutationResultSchema,
  RecruitingReviewMutationResultSchema,
  ReviewDetailSchema
} from "../../domain/schemas/recruiting-extended-results.js"
import {
  createRecruitingOpinionParamsJsonSchema,
  createRecruitingReviewParamsJsonSchema,
  deleteRecruitingOpinionParamsJsonSchema,
  deleteRecruitingReviewParamsJsonSchema,
  getRecruitingApplicantMatchParamsJsonSchema,
  getRecruitingOpinionParamsJsonSchema,
  getRecruitingReviewParamsJsonSchema,
  listRecruitingApplicantMatchesParamsJsonSchema,
  listRecruitingOpinionsParamsJsonSchema,
  listRecruitingReviewsParamsJsonSchema,
  parseCreateRecruitingOpinionParams,
  parseCreateRecruitingReviewParams,
  parseDeleteRecruitingOpinionParams,
  parseDeleteRecruitingReviewParams,
  parseGetRecruitingApplicantMatchParams,
  parseGetRecruitingOpinionParams,
  parseGetRecruitingReviewParams,
  parseListRecruitingApplicantMatchesParams,
  parseListRecruitingOpinionsParams,
  parseListRecruitingReviewsParams,
  parseUpdateRecruitingOpinionParams,
  parseUpdateRecruitingReviewParams,
  updateRecruitingOpinionParamsJsonSchema,
  updateRecruitingReviewParamsJsonSchema
} from "../../domain/schemas/recruiting-extended.js"
import {
  getRecruitingApplicantMatch,
  listRecruitingApplicantMatches
} from "../../huly/operations/recruiting-matches.js"
import {
  createRecruitingOpinion,
  deleteRecruitingOpinion,
  getRecruitingOpinion,
  listRecruitingOpinions,
  updateRecruitingOpinion
} from "../../huly/operations/recruiting-opinions.js"
import {
  createRecruitingReview,
  deleteRecruitingReview,
  getRecruitingReview,
  listRecruitingReviews,
  updateRecruitingReview
} from "../../huly/operations/recruiting-reviews.js"
import { createEncodedToolHandler, type RegisteredTool } from "./registry.js"

const CATEGORY = "recruiting" as const

export const recruitingExtendedTools: ReadonlyArray<RegisteredTool> = [
  {
    name: "list_recruiting_applicant_matches",
    description:
      "List read-only generated Recruiting applicant matches. ApplicantMatch fields are generated by Huly; this tool only reads them. Filter by candidate, complete state, vacancy/summary query, and limit.",
    category: CATEGORY,
    inputSchema: listRecruitingApplicantMatchesParamsJsonSchema,
    handler: createEncodedToolHandler(
      "list_recruiting_applicant_matches",
      parseListRecruitingApplicantMatchesParams,
      listRecruitingApplicantMatches,
      ListRecruitingApplicantMatchesResultSchema
    )
  },
  {
    name: "get_recruiting_applicant_match",
    description:
      "Get one read-only generated Recruiting applicant match by raw applicant-match _id. Returns candidate, complete state, generated vacancy text, summary, response markdown, and timestamps.",
    category: CATEGORY,
    inputSchema: getRecruitingApplicantMatchParamsJsonSchema,
    handler: createEncodedToolHandler(
      "get_recruiting_applicant_match",
      parseGetRecruitingApplicantMatchParams,
      getRecruitingApplicantMatch,
      ApplicantMatchDetailSchema
    )
  },
  {
    name: "list_recruiting_reviews",
    description:
      "List Recruiting reviews/interviews as stable refs. Filter by candidate, application, date range, title/verdict/location query, and limit. Review locators use raw _id, RVE-<number>, number, or exact title.",
    category: CATEGORY,
    inputSchema: listRecruitingReviewsParamsJsonSchema,
    handler: createEncodedToolHandler(
      "list_recruiting_reviews",
      parseListRecruitingReviewsParams,
      listRecruitingReviews,
      ListRecruitingReviewsResultSchema
    )
  },
  {
    name: "get_recruiting_review",
    description:
      "Get one Recruiting review by raw _id, RVE-<number>, bare number, or exact title. Optional candidate/application disambiguate. Returns schedule, markdown description, verdict, participant refs, company, application, and opinion count.",
    category: CATEGORY,
    inputSchema: getRecruitingReviewParamsJsonSchema,
    handler: createEncodedToolHandler(
      "get_recruiting_review",
      parseGetRecruitingReviewParams,
      getRecruitingReview,
      ReviewDetailSchema
    )
  },
  {
    name: "create_recruiting_review",
    description:
      "Create a Recruiting review/interview like the Huly UI: increments RVE sequence, attaches to the candidate reviews collection, stores markdown description as Huly markup, defaults dueDate to 30 minutes after date, and recruit-enables the person if needed.",
    category: CATEGORY,
    inputSchema: createRecruitingReviewParamsJsonSchema,
    handler: createEncodedToolHandler(
      "create_recruiting_review",
      parseCreateRecruitingReviewParams,
      createRecruitingReview,
      RecruitingReviewMutationResultSchema
    )
  },
  {
    name: "update_recruiting_review",
    description:
      "Update a Recruiting review. review accepts raw _id, RVE-<number>, number, or exact title; candidate/applicationContext only disambiguate. Pass null for description, verdict, application, company, or location to clear.",
    category: CATEGORY,
    inputSchema: updateRecruitingReviewParamsJsonSchema,
    handler: createEncodedToolHandler(
      "update_recruiting_review",
      parseUpdateRecruitingReviewParams,
      updateRecruitingReview,
      RecruitingReviewMutationResultSchema
    )
  },
  {
    name: "delete_recruiting_review",
    description:
      "Delete a Recruiting review with Huly removeCollection. review accepts raw _id, RVE-<number>, number, or exact title; candidate/application can disambiguate.",
    category: CATEGORY,
    inputSchema: deleteRecruitingReviewParamsJsonSchema,
    annotations: { destructiveHint: true, idempotentHint: false },
    handler: createEncodedToolHandler(
      "delete_recruiting_review",
      parseDeleteRecruitingReviewParams,
      deleteRecruitingReview,
      DeleteRecruitingReviewResultSchema
    )
  },
  {
    name: "list_recruiting_opinions",
    description:
      "List Recruiting opinions for one review. review accepts raw _id, RVE-<number>, bare number, or exact title. Opinion refs include OPE-<number>, parent review ref, and opinion value.",
    category: CATEGORY,
    inputSchema: listRecruitingOpinionsParamsJsonSchema,
    handler: createEncodedToolHandler(
      "list_recruiting_opinions",
      parseListRecruitingOpinionsParams,
      listRecruitingOpinions,
      ListRecruitingOpinionsResultSchema
    )
  },
  {
    name: "get_recruiting_opinion",
    description:
      "Get one Recruiting opinion by raw _id, OPE-<number>, or bare number. Pass review to disambiguate. Returns value, markdown description, comments/attachments counts, parent review ref, and timestamps.",
    category: CATEGORY,
    inputSchema: getRecruitingOpinionParamsJsonSchema,
    handler: createEncodedToolHandler(
      "get_recruiting_opinion",
      parseGetRecruitingOpinionParams,
      getRecruitingOpinion,
      OpinionDetailSchema
    )
  },
  {
    name: "create_recruiting_opinion",
    description:
      "Create a Recruiting opinion on one review. Increments the OPE sequence, attaches to the review opinions collection, and stores markdown description as Huly markup.",
    category: CATEGORY,
    inputSchema: createRecruitingOpinionParamsJsonSchema,
    handler: createEncodedToolHandler(
      "create_recruiting_opinion",
      parseCreateRecruitingOpinionParams,
      createRecruitingOpinion,
      RecruitingOpinionMutationResultSchema
    )
  },
  {
    name: "update_recruiting_opinion",
    description:
      "Update a Recruiting opinion value and/or markdown description. opinion accepts raw _id, OPE-<number>, or number; review can disambiguate. Pass null for description to clear it.",
    category: CATEGORY,
    inputSchema: updateRecruitingOpinionParamsJsonSchema,
    handler: createEncodedToolHandler(
      "update_recruiting_opinion",
      parseUpdateRecruitingOpinionParams,
      updateRecruitingOpinion,
      RecruitingOpinionMutationResultSchema
    )
  },
  {
    name: "delete_recruiting_opinion",
    description:
      "Delete a Recruiting opinion with Huly removeCollection. opinion accepts raw _id, OPE-<number>, or number; review can disambiguate.",
    category: CATEGORY,
    inputSchema: deleteRecruitingOpinionParamsJsonSchema,
    annotations: { destructiveHint: true, idempotentHint: false },
    handler: createEncodedToolHandler(
      "delete_recruiting_opinion",
      parseDeleteRecruitingOpinionParams,
      deleteRecruitingOpinion,
      DeleteRecruitingOpinionResultSchema
    )
  }
]
