import { Schema } from "effect"

import * as ApprovalRequestErrors from "./errors-approval-requests.js"
import { HulyAuthError, HulyConnectionError, HulyError, NoUpdateFieldsError } from "./errors-base.js"
import {
  BoardArchivedCardDeleteError,
  BoardCardIdentifierAmbiguousError,
  BoardCardNotFoundError,
  BoardIdentifierAmbiguousError,
  BoardLabelIdentifierAmbiguousError,
  BoardLabelNotFoundError,
  BoardMenuPageIdentifierAmbiguousError,
  BoardMenuPageNotFoundError,
  BoardModelSequenceMissingError,
  BoardMutationUnsupportedError,
  BoardNotFoundError,
  BoardProjectTypeIdentifierAmbiguousError,
  BoardProjectTypeNotFoundError,
  BoardSavedViewIdentifierAmbiguousError,
  BoardSavedViewNotFoundError,
  BoardStatusIdentifierAmbiguousError,
  BoardStatusNotFoundError,
  BoardTaskTypeIdentifierAmbiguousError,
  BoardTaskTypeNotFoundError,
  BoardViewletIdentifierAmbiguousError,
  BoardViewletNotFoundError
} from "./errors-boards.js"
import {
  CalendarNotAccessibleError,
  EventNotFoundError,
  RecurringEventNotFoundError,
  ScheduleNotFoundError
} from "./errors-calendar.js"
import { CardNotFoundError, CardSpaceNotFoundError, MasterTagNotFoundError } from "./errors-cards.js"
import {
  ContactChannelConflictError,
  ContactChannelIdentifierAmbiguousError,
  ContactChannelNotFoundError,
  InvalidContactChannelLocatorError,
  InvalidContactChannelValueError,
  InvalidContactProviderError,
  InvalidPersonUuidError,
  OrganizationIdentifierAmbiguousError,
  OrganizationNotFoundError,
  PersonIdentifierAmbiguousError,
  PersonNotFoundError
} from "./errors-contacts.js"
import { CustomFieldNotFoundError, CustomFieldObjectNotFoundError } from "./errors-custom-fields.js"
import {
  DocumentContentCorruptedError,
  DocumentEditModeError,
  DocumentEmptyContentError,
  DocumentNotFoundError,
  DocumentReferenceError,
  DocumentTextMultipleMatchesError,
  DocumentTextNotFoundError,
  TeamspaceNotFoundError
} from "./errors-documents.js"
import {
  DriveFileCommentNotFoundError,
  DriveFileNotFoundError,
  DriveFileVersionNotFoundError,
  DriveFolderNotEmptyError,
  DriveIdentifierAmbiguousError,
  DriveInvalidItemOperationError,
  DriveInvalidMoveError,
  DriveNotEmptyError,
  DriveNotFoundError,
  DriveParentNotFolderError,
  DrivePathAmbiguousError,
  DrivePathConflictError,
  DrivePathNotFoundError
} from "./errors-drive.js"
import {
  AttachmentNotFoundError,
  DrawingNotFoundError,
  FileFetchError,
  FileNotFoundError,
  FileTooLargeError,
  FileUploadError,
  InvalidContentTypeError,
  InvalidFileDataError,
  SavedAttachmentNotFoundError
} from "./errors-files.js"
import {
  AssociationConflictError,
  AssociationIdentifierAmbiguousError,
  AssociationInUseError,
  AssociationNotFoundError,
  AssociationSystemClassUnsupportedError,
  GenericObjectIdentifierAmbiguousError,
  GenericObjectLocatorInvalidError,
  GenericObjectNotFoundError,
  RelationCardinalityViolationError,
  RelationDirectionAmbiguousError,
  RelationEndpointClassMismatchError,
  RelationIdentifierAmbiguousError,
  RelationMutationUnsupportedError,
  RelationNotFoundError
} from "./errors-generic-associations.js"
import {
  InventoryCategoryIdentifierAmbiguousError,
  InventoryCategoryNotFoundError,
  InventoryConflictError,
  InventoryMutationUnsupportedError,
  InventoryNotEmptyError,
  InventoryProductCommentNotFoundError,
  InventoryProductIdentifierAmbiguousError,
  InventoryProductNotFoundError,
  InventoryVariantIdentifierAmbiguousError,
  InventoryVariantNotFoundError
} from "./errors-inventory.js"
import { TagCategoryNotFoundError, TagNotFoundError } from "./errors-labels.js"
import { FunnelNotFoundError, LeadNotFoundError } from "./errors-leads.js"
import { FloorNotFoundError, MeetingMinutesNotFoundError, RoomNotFoundError } from "./errors-love.js"
import {
  ActivityMessageNotFoundError,
  CannotDirectMessageSelfError,
  ChannelArchivedError,
  ChannelLastMemberRemovalError,
  ChannelLastOwnerRemovalError,
  ChannelNotFoundError,
  ChatMessageAttachmentNotFoundError,
  DirectMessageIdentifierAmbiguousError,
  DirectMessageNotFoundError,
  DirectMessageParticipantCountError,
  MessageNotFoundError,
  PersonNotAnEmployeeError,
  ReactionNotFoundError,
  SavedMessageNotFoundError,
  ThreadReplyNotFoundError
} from "./errors-messaging.js"
import {
  NotificationContextNotFoundError,
  NotificationNotFoundError,
  NotificationPersonSpaceNotFoundError,
  NotificationProviderNotConfigurableError,
  NotificationTypeNotFoundError
} from "./errors-notifications.js"
import { TodoIdentifierAmbiguousError, TodoNotFoundError, TodoWorkSlotNotFoundError } from "./errors-planner.js"
import {
  ProcessCardIdentifierAmbiguousError,
  ProcessCardNotFoundError,
  ProcessExecutionNotCancellableError,
  ProcessExecutionNotFoundError,
  ProcessIdentifierAmbiguousError,
  ProcessInitialStateNotFoundError,
  ProcessMasterTagAmbiguousError,
  ProcessMasterTagNotFoundError,
  ProcessNotFoundError,
  ProcessParallelExecutionForbiddenError
} from "./errors-processes.js"
import {
  RecruitingApplicantIdentifierAmbiguousError,
  RecruitingApplicantMatchNotFoundError,
  RecruitingApplicantNotFoundError,
  RecruitingAttachmentNotFoundError,
  RecruitingCandidateNotFoundError,
  RecruitingCommentNotFoundError,
  RecruitingDuplicateApplicantError,
  RecruitingIssueLocatorInvalidError,
  RecruitingModelMissingError,
  RecruitingMutationUnsupportedError,
  RecruitingOpinionIdentifierAmbiguousError,
  RecruitingOpinionNotFoundError,
  RecruitingReviewIdentifierAmbiguousError,
  RecruitingReviewNotFoundError,
  RecruitingVacancyIdentifierAmbiguousError,
  RecruitingVacancyNotFoundError,
  RecruitingVacancyTypeNotFoundError
} from "./errors-recruiting.js"
import { HulyClassNotFoundError } from "./errors-sdk-discovery.js"
import {
  SpaceIdentifierAmbiguousError,
  SpaceNotFoundError,
  SpaceNotTypedError,
  SpaceRoleAssignmentsMalformedError,
  SpaceRoleIdentifierAmbiguousError,
  SpaceRoleNotFoundError,
  SpaceTypeIdentifierAmbiguousError,
  SpaceTypeNotFoundError
} from "./errors-spaces.js"
import {
  MessageTemplateCategoryIdentifierAmbiguousError,
  MessageTemplateCategoryNotFoundError,
  MessageTemplateIdentifierAmbiguousError,
  MessageTemplateNotFoundError,
  TemplateFieldCategoryIdentifierAmbiguousError,
  TemplateFieldCategoryNotFoundError
} from "./errors-templates.js"
import {
  TestCaseNotFoundError,
  TestPlanItemNotFoundError,
  TestPlanNotFoundError,
  TestProjectNotFoundError,
  TestResultNotFoundError,
  TestRunNotFoundError,
  TestSuiteNotFoundError
} from "./errors-test-management.js"
import {
  CommentNotFoundError,
  ComponentNotFoundError,
  InvalidStatusError,
  IssueNotFoundError,
  IssueTemplateNotFoundError,
  MilestoneNotFoundError,
  ProjectNotFoundError,
  TemplateChildNotFoundError
} from "./errors-tracker.js"
import {
  FilteredViewIdentifierAmbiguousError,
  FilteredViewNotFoundError,
  ViewletIdentifierAmbiguousError,
  ViewletNotFoundError
} from "./errors-views.js"

export const HulyDomainError = Schema.Union(
  HulyError,
  NoUpdateFieldsError,
  HulyConnectionError,
  HulyAuthError,
  ApprovalRequestErrors.ApprovalRequestNotFoundError,
  ApprovalRequestErrors.ApprovalRequestTargetNotFoundError,
  ApprovalRequestErrors.ApprovalRequestInvalidApprovalThresholdError,
  ApprovalRequestErrors.ApprovalRequestMutationUnsupportedError,
  ApprovalRequestErrors.ApprovalRequestNotActiveError,
  ApprovalRequestErrors.ApprovalRequestApproverNotRequestedError,
  ApprovalRequestErrors.ApprovalRequestCancelUnauthorizedError,
  BoardNotFoundError,
  BoardIdentifierAmbiguousError,
  BoardCardNotFoundError,
  BoardCardIdentifierAmbiguousError,
  BoardProjectTypeNotFoundError,
  BoardProjectTypeIdentifierAmbiguousError,
  BoardTaskTypeNotFoundError,
  BoardTaskTypeIdentifierAmbiguousError,
  BoardStatusNotFoundError,
  BoardStatusIdentifierAmbiguousError,
  BoardArchivedCardDeleteError,
  BoardModelSequenceMissingError,
  BoardMutationUnsupportedError,
  BoardLabelNotFoundError,
  BoardLabelIdentifierAmbiguousError,
  BoardSavedViewNotFoundError,
  BoardSavedViewIdentifierAmbiguousError,
  BoardMenuPageNotFoundError,
  BoardMenuPageIdentifierAmbiguousError,
  BoardViewletNotFoundError,
  BoardViewletIdentifierAmbiguousError,
  FilteredViewNotFoundError,
  FilteredViewIdentifierAmbiguousError,
  ViewletNotFoundError,
  ViewletIdentifierAmbiguousError,
  IssueNotFoundError,
  ProjectNotFoundError,
  InvalidStatusError,
  ContactChannelConflictError,
  ContactChannelIdentifierAmbiguousError,
  ContactChannelNotFoundError,
  InvalidContactChannelLocatorError,
  InvalidContactChannelValueError,
  PersonIdentifierAmbiguousError,
  PersonNotFoundError,
  OrganizationNotFoundError,
  OrganizationIdentifierAmbiguousError,
  InvalidContactProviderError,
  FileUploadError,
  InvalidFileDataError,
  FileNotFoundError,
  FileFetchError,
  TeamspaceNotFoundError,
  DocumentNotFoundError,
  DocumentTextNotFoundError,
  DocumentTextMultipleMatchesError,
  DocumentEmptyContentError,
  DocumentContentCorruptedError,
  DocumentEditModeError,
  DocumentReferenceError,
  CommentNotFoundError,
  MilestoneNotFoundError,
  ChannelNotFoundError,
  ChannelArchivedError,
  ChannelLastMemberRemovalError,
  ChannelLastOwnerRemovalError,
  CannotDirectMessageSelfError,
  DirectMessageIdentifierAmbiguousError,
  DirectMessageNotFoundError,
  DirectMessageParticipantCountError,
  MessageNotFoundError,
  ChatMessageAttachmentNotFoundError,
  PersonNotAnEmployeeError,
  ThreadReplyNotFoundError,
  CalendarNotAccessibleError,
  EventNotFoundError,
  RecurringEventNotFoundError,
  ScheduleNotFoundError,
  ActivityMessageNotFoundError,
  ReactionNotFoundError,
  SavedMessageNotFoundError,
  AttachmentNotFoundError,
  SavedAttachmentNotFoundError,
  DrawingNotFoundError,
  CardSpaceNotFoundError,
  CardNotFoundError,
  MasterTagNotFoundError,
  TagNotFoundError,
  TagCategoryNotFoundError,
  InventoryCategoryNotFoundError,
  InventoryProductNotFoundError,
  InventoryVariantNotFoundError,
  InventoryCategoryIdentifierAmbiguousError,
  InventoryProductIdentifierAmbiguousError,
  InventoryVariantIdentifierAmbiguousError,
  InventoryConflictError,
  InventoryNotEmptyError,
  InventoryMutationUnsupportedError,
  InventoryProductCommentNotFoundError,
  TestProjectNotFoundError,
  TestSuiteNotFoundError,
  TestCaseNotFoundError,
  TestPlanNotFoundError,
  TestRunNotFoundError,
  TestResultNotFoundError,
  TestPlanItemNotFoundError,
  ComponentNotFoundError,
  CustomFieldNotFoundError,
  CustomFieldObjectNotFoundError,
  IssueTemplateNotFoundError,
  TemplateChildNotFoundError,
  NotificationNotFoundError,
  NotificationContextNotFoundError,
  NotificationPersonSpaceNotFoundError,
  NotificationTypeNotFoundError,
  NotificationProviderNotConfigurableError,
  InvalidPersonUuidError,
  FunnelNotFoundError,
  LeadNotFoundError,
  FloorNotFoundError,
  RoomNotFoundError,
  MeetingMinutesNotFoundError,
  FileTooLargeError,
  InvalidContentTypeError,
  ProcessNotFoundError,
  ProcessIdentifierAmbiguousError,
  ProcessMasterTagAmbiguousError,
  ProcessMasterTagNotFoundError,
  ProcessCardIdentifierAmbiguousError,
  ProcessCardNotFoundError,
  ProcessInitialStateNotFoundError,
  ProcessParallelExecutionForbiddenError,
  ProcessExecutionNotFoundError,
  ProcessExecutionNotCancellableError,
  RecruitingApplicantIdentifierAmbiguousError,
  RecruitingApplicantMatchNotFoundError,
  RecruitingApplicantNotFoundError,
  RecruitingAttachmentNotFoundError,
  RecruitingCandidateNotFoundError,
  RecruitingCommentNotFoundError,
  RecruitingDuplicateApplicantError,
  RecruitingIssueLocatorInvalidError,
  RecruitingModelMissingError,
  RecruitingMutationUnsupportedError,
  RecruitingOpinionIdentifierAmbiguousError,
  RecruitingOpinionNotFoundError,
  RecruitingReviewIdentifierAmbiguousError,
  RecruitingReviewNotFoundError,
  RecruitingVacancyIdentifierAmbiguousError,
  RecruitingVacancyNotFoundError,
  RecruitingVacancyTypeNotFoundError,
  AssociationNotFoundError,
  AssociationIdentifierAmbiguousError,
  AssociationSystemClassUnsupportedError,
  AssociationConflictError,
  AssociationInUseError,
  RelationNotFoundError,
  RelationIdentifierAmbiguousError,
  RelationMutationUnsupportedError,
  RelationCardinalityViolationError,
  RelationDirectionAmbiguousError,
  RelationEndpointClassMismatchError,
  GenericObjectIdentifierAmbiguousError,
  GenericObjectLocatorInvalidError,
  GenericObjectNotFoundError,
  HulyClassNotFoundError,
  SpaceNotFoundError,
  SpaceIdentifierAmbiguousError,
  SpaceNotTypedError,
  SpaceRoleNotFoundError,
  SpaceRoleIdentifierAmbiguousError,
  SpaceRoleAssignmentsMalformedError,
  SpaceTypeNotFoundError,
  SpaceTypeIdentifierAmbiguousError,
  TodoNotFoundError,
  TodoIdentifierAmbiguousError,
  TodoWorkSlotNotFoundError,
  DriveNotFoundError,
  DriveIdentifierAmbiguousError,
  DrivePathNotFoundError,
  DrivePathAmbiguousError,
  DriveParentNotFolderError,
  DriveFileCommentNotFoundError,
  DriveFileNotFoundError,
  DriveFileVersionNotFoundError,
  DrivePathConflictError,
  DriveInvalidMoveError,
  DriveInvalidItemOperationError,
  DriveFolderNotEmptyError,
  DriveNotEmptyError,
  MessageTemplateCategoryNotFoundError,
  MessageTemplateCategoryIdentifierAmbiguousError,
  MessageTemplateNotFoundError,
  MessageTemplateIdentifierAmbiguousError,
  TemplateFieldCategoryNotFoundError,
  TemplateFieldCategoryIdentifierAmbiguousError
)

export type HulyDomainError = Schema.Schema.Type<typeof HulyDomainError>
